/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    media: Media;
    pages: Page;
    systems: System;
    solutions: Solution;
    projects: Project;
    documents: Document;
    suppliers: Supplier;
    offices: Office;
    leads: Lead;
    'other-products': OtherProduct;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    systems: SystemsSelect<false> | SystemsSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    offices: OfficesSelect<false> | OfficesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'other-products': OtherProductsSelect<false> | OtherProductsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-settings': SiteSetting;
    homepage: Homepage;
    'solutions-page': SolutionsPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'solutions-page': SolutionsPageSelect<false> | SolutionsPageSelect<true>;
  };
  locale: null;
  user: Admin & {
    collection: 'admins';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  name?: string | null;
  role: 'administrator' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  title: string;
  /**
   * Кратко опишите изображение для поисковиков и доступности.
   */
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Например: about или privacy.
   */
  slug: string;
  eyebrow?: string | null;
  heroTitle: string;
  heroDescription?: string | null;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "systems".
 */
export interface System {
  id: number;
  name: string;
  slug: string;
  code: string;
  category: 'warm' | 'cold' | 'facade';
  categoryLabel: string;
  status: 'available' | 'development';
  statusLabel: string;
  tagline: string;
  summary: string;
  image?: (number | null) | Media;
  legacyImage?: string | null;
  audience?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  applications?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  constructionTypes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image?: (number | null) | Media;
        legacyImage?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  specifications?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  title: string;
  slug: string;
  description: string;
  order?: number | null;
  systems?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  objects?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Создавайте проекты и загружайте главную фотографию и галерею прямо здесь. Город можно не заполнять.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  category: string;
  system: string;
  /**
   * Необязательное поле.
   */
  city?: string | null;
  note?: string | null;
  order?: number | null;
  isReal: boolean;
  /**
   * Обложка проекта на странице «Проекты». Для нового опубликованного проекта обязательна.
   */
  image?: (number | null) | Media;
  legacyImage?: string | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Загружайте каталоги, сертификаты и технические файлы. Формат и размер файла заполняются автоматически.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  slug: string;
  system: string;
  category: string;
  format: string;
  size?: string | null;
  version?: string | null;
  documentDate?: string | null;
  description?: string | null;
  order?: number | null;
  /**
   * Меняется автоматически: после публикации с загруженным файлом документ появится на сайте.
   */
  status?: ('published' | 'demo') | null;
  /**
   * PDF, ZIP, DWG, DOCX, XLSX и другие разрешённые технические файлы. Для статуса «Опубликован» обязателен.
   */
  file?: (number | null) | Media;
  /**
   * Изображение для карточки в разделе «Документация».
   */
  previewImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Реальные поставщики и технологические партнёры. Добавляйте только подтверждённые компании и бренды.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: number;
  name: string;
  slug: string;
  /**
   * Например: поставщик фурнитуры или производитель стеклопакетов.
   */
  role: string;
  description?: string | null;
  website?: string | null;
  logo?: (number | null) | Media;
  /**
   * Для белого логотипа ТБМ выберите фирменную зелёную подложку.
   */
  logoTheme?: ('light' | 'dark' | 'green') | null;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offices".
 */
export interface Office {
  id: number;
  region: string;
  city: string;
  address: string;
  phone: string;
  workingHours?: string | null;
  routeUrl?: string | null;
  /**
   * Например: 44.0486
   */
  latitude?: number | null;
  /**
   * Например: 43.0594
   */
  longitude?: number | null;
  photo?: (number | null) | Media;
  services?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  cardStyle?: ('light' | 'dark' | 'accent') | null;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone: string;
  city: string;
  sourcePage: string;
  email?: string | null;
  company?: string | null;
  role?: string | null;
  message?: string | null;
  crmStatus: 'disabled' | 'pending' | 'sent' | 'failed';
  crmAttempts?: number | null;
  crmResponse?: string | null;
  crmUpdatedAt?: string | null;
  status: 'new' | 'in_progress' | 'completed' | 'spam';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "other-products".
 */
export interface OtherProduct {
  id: number;
  title: string;
  slug: string;
  /**
   * Короткий текст для каталога продуктов.
   */
  shortDescription?: string | null;
  description: string;
  image?: (number | null) | Media;
  legacyImage?: string | null;
  applications?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  technicalCharacteristics?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  advantages?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'systems';
        value: number | System;
      } | null)
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: number | Supplier;
      } | null)
    | ({
        relationTo: 'offices';
        value: number | Office;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'other-products';
        value: number | OtherProduct;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  eyebrow?: T;
  heroTitle?: T;
  heroDescription?: T;
  heroImage?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "systems_select".
 */
export interface SystemsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  code?: T;
  category?: T;
  categoryLabel?: T;
  status?: T;
  statusLabel?: T;
  tagline?: T;
  summary?: T;
  image?: T;
  legacyImage?: T;
  audience?:
    | T
    | {
        text?: T;
        id?: T;
      };
  applications?:
    | T
    | {
        text?: T;
        id?: T;
      };
  constructionTypes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        legacyImage?: T;
        alt?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  order?: T;
  systems?:
    | T
    | {
        name?: T;
        id?: T;
      };
  objects?:
    | T
    | {
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  system?: T;
  city?: T;
  note?: T;
  order?: T;
  isReal?: T;
  image?: T;
  legacyImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  system?: T;
  category?: T;
  format?: T;
  size?: T;
  version?: T;
  documentDate?: T;
  description?: T;
  order?: T;
  status?: T;
  file?: T;
  previewImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  description?: T;
  website?: T;
  logo?: T;
  logoTheme?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offices_select".
 */
export interface OfficesSelect<T extends boolean = true> {
  region?: T;
  city?: T;
  address?: T;
  phone?: T;
  workingHours?: T;
  routeUrl?: T;
  latitude?: T;
  longitude?: T;
  photo?: T;
  services?:
    | T
    | {
        title?: T;
        id?: T;
      };
  cardStyle?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  city?: T;
  sourcePage?: T;
  email?: T;
  company?: T;
  role?: T;
  message?: T;
  crmStatus?: T;
  crmAttempts?: T;
  crmResponse?: T;
  crmUpdatedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "other-products_select".
 */
export interface OtherProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  image?: T;
  legacyImage?: T;
  applications?:
    | T
    | {
        title?: T;
        id?: T;
      };
  technicalCharacteristics?:
    | T
    | {
        title?: T;
        id?: T;
      };
  advantages?:
    | T
    | {
        title?: T;
        id?: T;
      };
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  description: string;
  phone: string;
  email?: string | null;
  address: string;
  logo?: (number | null) | Media;
  navigation?:
    | {
        label: string;
        href: string;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  socials?: {
    telegram?: string | null;
    vk?: string | null;
  };
  /**
   * Заявка сначала сохраняется в CMS, затем отправляется в CRM. Токены и секреты задаются только переменными окружения сервера.
   */
  crm?: {
    enabled?: boolean | null;
    mode?: ('webhook' | 'api') | null;
    /**
     * Можно оставить пустым и задать CRM_WEBHOOK_URL или CRM_API_URL на сервере.
     */
    endpoint?: string | null;
  };
  seo?: {
    defaultTitle?: string | null;
    defaultDescription?: string | null;
  };
  seeded?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  eyebrow: string;
  title: string;
  description: string;
  heroImage?: (number | null) | Media;
  legacyHeroImage?: string | null;
  /**
   * Баннер появляется справа через одну секунду после открытия главной страницы.
   */
  promoBanner?: {
    enabled?: boolean | null;
    /**
     * Необязательное прозрачное PNG/WebP. Основной текст баннера формируется сайтом.
     */
    image?: (number | null) | Media;
    legacyImage?: string | null;
    discount?: string | null;
    title?: string | null;
    subtitle?: string | null;
    deadline?: string | null;
    /**
     * Оставьте пустым, если баннер отключается вручную.
     */
    expiresAt?: string | null;
    footnote?: string | null;
    alt?: string | null;
    href?: string | null;
  };
  primaryAction?: {
    label?: string | null;
    href?: string | null;
  };
  secondaryAction?: {
    label?: string | null;
    href?: string | null;
  };
  facts?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  sectionTitles?: {
    systems?: string | null;
    solutions?: string | null;
    projects?: string | null;
    contact?: string | null;
  };
  seeded?: boolean | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions-page".
 */
export interface SolutionsPage {
  id: number;
  doorPrices?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    /**
     * Четыре карточки выводятся на странице в указанном порядке.
     */
    cards?:
      | {
          title: string;
          note: string;
          /**
           * Оставьте пустым, если карточке не нужна прежняя цена.
           */
          oldPrice?: string | null;
          price: string;
          variant: 'split' | 'panoramic' | 'asymmetric' | 'double';
          id?: string | null;
        }[]
      | null;
  };
  windowPrices?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    /**
     * Три карточки выводятся на странице в указанном порядке.
     */
    cards?:
      | {
          title: string;
          note: string;
          /**
           * Оставьте пустым, если карточке не нужна прежняя цена.
           */
          oldPrice?: string | null;
          price: string;
          variant: 'single' | 'double' | 'triple';
          id?: string | null;
        }[]
      | null;
  };
  seeded?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  description?: T;
  phone?: T;
  email?: T;
  address?: T;
  logo?: T;
  navigation?:
    | T
    | {
        label?: T;
        href?: T;
        enabled?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        telegram?: T;
        vk?: T;
      };
  crm?:
    | T
    | {
        enabled?: T;
        mode?: T;
        endpoint?: T;
      };
  seo?:
    | T
    | {
        defaultTitle?: T;
        defaultDescription?: T;
      };
  seeded?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  heroImage?: T;
  legacyHeroImage?: T;
  promoBanner?:
    | T
    | {
        enabled?: T;
        image?: T;
        legacyImage?: T;
        discount?: T;
        title?: T;
        subtitle?: T;
        deadline?: T;
        expiresAt?: T;
        footnote?: T;
        alt?: T;
        href?: T;
      };
  primaryAction?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryAction?:
    | T
    | {
        label?: T;
        href?: T;
      };
  facts?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  sectionTitles?:
    | T
    | {
        systems?: T;
        solutions?: T;
        projects?: T;
        contact?: T;
      };
  seeded?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions-page_select".
 */
export interface SolutionsPageSelect<T extends boolean = true> {
  doorPrices?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
        cards?:
          | T
          | {
              title?: T;
              note?: T;
              oldPrice?: T;
              price?: T;
              variant?: T;
              id?: T;
            };
      };
  windowPrices?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
        cards?:
          | T
          | {
              title?: T;
              note?: T;
              oldPrice?: T;
              price?: T;
              variant?: T;
              id?: T;
            };
      };
  seeded?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}